name: Clang Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-check:
    container:
      image:  loiczimm/ubuntu2204-qt6:latest
    runs-on:  [ ubuntu-latest ]

    steps:
    - name: Setup environment variables
      run: |
        echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - run: |
        apt-get update
        apt-get install clang-format -y

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ZIMMLDEV_PAT }}

    - name: Run clang-format check
      run: |
        cd $GITHUB_WORKSPACE
        scripts/check-clang.sh
